### ISSUE TITLE
Error while building Mynewt apps based examples

### ISSUE THREAD

**Issue by ghost** [Decawave/mynewt-dw1000-core#14]
Greetings
I went through getting started and tutorial guide of Mynewt.
I was successfully able to build the blinky example.
But while building Decawave apps as given on the website: https://github.com/Decawave/mynewt-dw1000-apps

I get the following error.

Building target targets/dwm1001_boot1
Compiling repos/apache-mynewt-core/boot/bootutil/src/bootutil_misc.c
Error: repos/apache-mynewt-core/boot/bootutil/src/image_ec.c:24:15: error: missing binary operator before token “(”
#if MYNEWT_VAL(BOOTUTIL_SIGN_EC)
^
image_ec.o: repos/apache-mynewt-core/boot/bootutil/src/image_ec.c 
os/mynewt.h

Kindly help me out to solve this issue

Thanks & regards
Asmita

**Comment by ncasaril** [comment]
Hi Asmita,
Sorry for the delay in getting back to you. 
What version of mynewt are you using? We've only tested the examples up to version 1.5 of mynewt-core. 

I'll be working on getting them up to date with 1.6 in the near future but for now please use 1.5. 

Thanks,
Niklas

**Comment by ghost** [comment]
Hello
Thanks for your response. Now I am successfully able to run the examples using Ubuntu.

Now I am facing problem at 
https://github.com/Decawave/mynewt-dw1000-apps/issues/18

Hope you can suggest something for it.

Regards
Asmita
